// FR-11: Separate PDFs for P&L, Cash flow, and Income statement.
import type { ReportsData } from '../services/reportsService';
import { formatRWF } from './formatCurrency';

const BASE_STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1f2937; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .subtitle { font-size: 14px; color: #6b7280; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
  th { font-size: 12px; color: #6b7280; font-weight: 500; }
  td { font-size: 14px; }
  .footer { margin-top: 24px; font-size: 12px; color: #9ca3af; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 16px; font-weight: 600; margin-bottom: 12px; }
  .total-row { font-weight: 700; border-top: 2px solid #1f2937; }
  .amount-positive { color: #22C55E; }
  .amount-negative { color: #EF4444; }
`;

function escapeHtml(text: string): string {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export type PlPdfLabels = {
  profitAndLoss: string;
  revenue: string;
  expenses: string;
  expensesByCategory: string;
  netProfit: string;
  transactions: string;
};

/** Profit & Loss: Revenue, expenses by category, net profit. */
export function buildProfitLossHtml(data: ReportsData, labels: PlPdfLabels): string {
  const categoryRows = data.categories
    .filter((c) => c.amount > 0)
    .map((c) => `<tr><td>${escapeHtml(c.name)}</td><td>${c.count}</td><td class="amount-negative">${formatRWF(c.amount)}</td></tr>`)
    .join('');

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${escapeHtml(labels.profitAndLoss)}</title><style>${BASE_STYLES}</style></head>
<body>
  <h1>${escapeHtml(labels.profitAndLoss)}</h1>
  <p class="subtitle">${new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}</p>
  <div class="section">
    <div class="section-title">${escapeHtml(labels.revenue)}</div>
    <table><tr><td>${escapeHtml(labels.revenue)}</td><td class="amount-positive">${formatRWF(data.totalIncome)}</td></tr></table>
  </div>
  <div class="section">
    <div class="section-title">${escapeHtml(labels.expenses)}</div>
    <table>
      <thead><tr><th>${escapeHtml(labels.expensesByCategory)}</th><th>${escapeHtml(labels.transactions)}</th><th>Amount</th></tr></thead>
      <tbody>${categoryRows || '<tr><td colspan="3">No data</td></tr>'}</tbody>
      <tr class="total-row"><td colspan="2">Total ${escapeHtml(labels.expenses)}</td><td class="amount-negative">${formatRWF(data.totalExpense)}</td></tr>
    </table>
  </div>
  <div class="section">
    <table><tr class="total-row"><td>${escapeHtml(labels.netProfit)}</td><td class="amount-positive">${formatRWF(data.net)}</td></tr></table>
  </div>
  <p class="footer">Generated by MobiFlow • ${new Date().toLocaleDateString()}</p>
</body></html>
`.trim();
}

export type CashFlowPdfLabels = {
  cashFlowStatement: string;
  cashInflows: string;
  cashOutflows: string;
  netCashFlow: string;
  period: string;
  income: string;
  expense: string;
};

/** Cash flow: Inflows (income), outflows (expense), net change; optional period breakdown. */
export function buildCashFlowHtml(data: ReportsData, labels: CashFlowPdfLabels): string {
  const rows = data.stackedChartData.labels
    .map((label, i) => {
      const in_ = (data.stackedChartData.data[i]?.[0] ?? 0) * 1000;
      const out = (data.stackedChartData.data[i]?.[1] ?? 0) * 1000;
      return `<tr><td>${escapeHtml(label)}</td><td class="amount-positive">${formatRWF(in_)}</td><td class="amount-negative">${formatRWF(out)}</td></tr>`;
    })
    .join('');

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${escapeHtml(labels.cashFlowStatement)}</title><style>${BASE_STYLES}</style></head>
<body>
  <h1>${escapeHtml(labels.cashFlowStatement)}</h1>
  <p class="subtitle">${labels.period}: Last 7 days • ${new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}</p>
  <div class="section">
    <table>
      <tr><td>${escapeHtml(labels.cashInflows)}</td><td class="amount-positive">${formatRWF(data.totalIncome)}</td></tr>
      <tr><td>${escapeHtml(labels.cashOutflows)}</td><td class="amount-negative">${formatRWF(data.totalExpense)}</td></tr>
      <tr class="total-row"><td>${escapeHtml(labels.netCashFlow)}</td><td class="amount-positive">${formatRWF(data.net)}</td></tr>
    </table>
  </div>
  <div class="section">
    <div class="section-title">${escapeHtml(labels.period)} (daily)</div>
    <table>
      <thead><tr><th>Day</th><th>${escapeHtml(labels.income)}</th><th>${escapeHtml(labels.expense)}</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="3">No data</td></tr>'}</tbody>
    </table>
  </div>
  <p class="footer">Generated by MobiFlow • ${new Date().toLocaleDateString()}</p>
</body></html>
`.trim();
}

export type IncomeStatementPdfLabels = {
  incomeStatement: string;
  revenue: string;
  expenses: string;
  netIncome: string;
  expensesByCategory: string;
  transactions: string;
};

/** Income statement: Same structure as P&L (revenue - expenses = net income), formal title for banks/MFIs. */
export function buildIncomeStatementHtml(data: ReportsData, labels: IncomeStatementPdfLabels): string {
  const categoryRows = data.categories
    .filter((c) => c.amount > 0)
    .map((c) => `<tr><td>${escapeHtml(c.name)}</td><td>${c.count}</td><td class="amount-negative">${formatRWF(c.amount)}</td></tr>`)
    .join('');

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${escapeHtml(labels.incomeStatement)}</title><style>${BASE_STYLES}</style></head>
<body>
  <h1>${escapeHtml(labels.incomeStatement)}</h1>
  <p class="subtitle">${new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}</p>
  <div class="section">
    <table><tr><td>${escapeHtml(labels.revenue)}</td><td class="amount-positive">${formatRWF(data.totalIncome)}</td></tr></table>
  </div>
  <div class="section">
    <div class="section-title">${escapeHtml(labels.expenses)}</div>
    <table>
      <thead><tr><th>${escapeHtml(labels.expensesByCategory)}</th><th>${escapeHtml(labels.transactions)}</th><th>Amount</th></tr></thead>
      <tbody>${categoryRows || '<tr><td colspan="3">No data</td></tr>'}</tbody>
      <tr class="total-row"><td colspan="2">Total ${escapeHtml(labels.expenses)}</td><td class="amount-negative">${formatRWF(data.totalExpense)}</td></tr>
    </table>
  </div>
  <div class="section">
    <table><tr class="total-row"><td>${escapeHtml(labels.netIncome)}</td><td class="amount-positive">${formatRWF(data.net)}</td></tr></table>
  </div>
  <p class="footer">Generated by MobiFlow • ${new Date().toLocaleDateString()}</p>
</body></html>
`.trim();
}
