// Builds the HTML for the Reports PDF so the user can download or share it.
import type { ReportsData } from '../services/reportsService';
import { formatRWF } from './formatCurrency';

export type ReportsPdfLabels = {
  reports: string;
  reportsSubtitle: string;
  totalIncome: string;
  totalExpense: string;
  net: string;
  incomeVsExpense7Days: string;
  income: string;
  expense: string;
  expensesByCategory: string;
  transactions: string;
};

export function buildReportsHtml(data: ReportsData, labels: ReportsPdfLabels): string {
  const rows = data.stackedChartData.labels
    .map((label, i) => {
      const income = (data.stackedChartData.data[i]?.[0] ?? 0) * 1000;
      const expense = (data.stackedChartData.data[i]?.[1] ?? 0) * 1000;
      return `<tr>
        <td>${escapeHtml(label)}</td>
        <td style="color:#22C55E">${formatRWF(income)}</td>
        <td style="color:#EF4444">${formatRWF(expense)}</td>
      </tr>`;
    })
    .join('');

  const categoryRows = data.categories
    .filter((c) => c.amount > 0)
    .map(
      (c) =>
        `<tr>
          <td>${escapeHtml(c.name)}</td>
          <td>${c.count}</td>
          <td>${formatRWF(c.amount)}</td>
        </tr>`
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${labels.reports}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1f2937; }
    h1 { font-size: 20px; margin-bottom: 4px; }
    .subtitle { font-size: 14px; color: #6b7280; margin-bottom: 24px; }
    .summary { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
    .summary-card { flex: 1; min-width: 100px; border: 1px solid #e5e7eb; border-radius: 12px; padding: 14px; }
    .summary-label { font-size: 11px; color: #6b7280; margin-bottom: 4px; }
    .summary-value { font-size: 14px; font-weight: 700; }
    .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; margin-bottom: 20px; }
    .card-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { font-size: 12px; color: #6b7280; font-weight: 500; }
    td { font-size: 14px; }
    .footer { margin-top: 24px; font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <h1>${labels.reports}</h1>
  <p class="subtitle">${labels.reportsSubtitle}</p>

  <div class="summary">
    <div class="summary-card">
      <div class="summary-label">${labels.totalIncome}</div>
      <div class="summary-value" style="color:#22C55E">${formatRWF(data.totalIncome, { compact: true })}</div>
    </div>
    <div class="summary-card">
      <div class="summary-label">${labels.totalExpense}</div>
      <div class="summary-value" style="color:#EF4444">${formatRWF(data.totalExpense, { compact: true })}</div>
    </div>
    <div class="summary-card">
      <div class="summary-label">${labels.net}</div>
      <div class="summary-value" style="color:#22C55E">${formatRWF(data.net, { compact: true })}</div>
    </div>
  </div>

  <div class="card">
    <div class="card-title">${labels.incomeVsExpense7Days}</div>
    <table>
      <thead>
        <tr><th>Day</th><th>${labels.income}</th><th>${labels.expense}</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </div>

  <div class="card">
    <div class="card-title">${labels.expensesByCategory}</div>
    <table>
      <thead>
        <tr><th>Category</th><th>${labels.transactions}</th><th>Amount</th></tr>
      </thead>
      <tbody>${categoryRows || '<tr><td colspan="3">No data</td></tr>'}</tbody>
    </table>
  </div>

  <p class="footer">Generated by MobiFlow • ${new Date().toLocaleDateString()}</p>
</body>
</html>
`.trim();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
